// <auto-generated />
namespace SCE___FINAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class courseReq : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(courseReq));
        
        string IMigrationMetadata.Id
        {
            get { return "202001092043122_courseReq"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
